import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import ThreeScene from "../components/threejs/ThreeScene";

const Home: NextPage = () => {
  const [color, setColor] = useState("hotpink");
  return (
    <div className="h-screen">
      <Head>
        <title>WIP 3JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center gap-[4px] sticky bottom-10">
        <span className="font-semibold text-transparent text-3xl bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
          Type a color
        </span>

        <input
          className="bg-gray-100 rounded-lg p-2 w-[98%] sm:w-[200px]"
          onChange={(e) => setColor(e.target.value)}
        ></input>
      </div>
    </div>
  );
};

export default Home;
